
@echo off
C:\Windows\System32\tasklist /FI "IMAGENAME eq arma3server_x64.exe" 2>NUL | C:\Windows\System32\find /I /N "arma3server_x64.exe">NUL
echo Server monitored is not running, will be started now
start "ArmA3" /min /wait "C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Server\arma3server_x64.exe" -port=2302 -showScriptErrors -filePatching -world=empty -nosplash -skipIntro -autoinit -loadMissionToMemory "-profiles=C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Server\Profiles" "-config=C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Server\config.cfg" "-cfg=C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Server\basic.cfg"  "-serverMod=" -bandwidthAlg=2 "-mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@ALiVE;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Core;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Maps;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Enhanced Movement;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@MCC Sandbox 4 -  Mission Making The Easy Way;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Project OPFOR;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSAFRF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSGREF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSSAF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSUSAF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Immersion Cigs;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@NIArms All in One;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@NIArms All in One - RHS Compatibility;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@NIArms Core;D:\Games\Steam\steamapps\common\Arma 3\@Prei Khmaoch Luong;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@The_Unsung_Vietnam_War_Mod;"

echo Server started succesfully

// C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Simple Single Player Cheat Menu;
// C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CH View Distance;